# ============================================================================
# dev-changelog
# ============================================================================
# Weekly engineering changelog from merged PRs, posted to Slack.
# Runs every Monday at 9 AM, fetches all PRs merged in the last 7 days
# across monitored repositories, and generates a structured changelog
# using Claude. Output uses ---THREAD--- delimiter for Slack Block Kit
# threading (Part 1: channel summary, Part 2: detailed thread reply).
#
# Pipeline: cron --> github-merged-prs --> 2x claude-code --> slack
#
# Requires GITHUB_TOKEN env var for GitHub API access.
# Requires SLACK_WEBHOOK_URL env var for Slack delivery.
# ============================================================================

name: dev-changelog
description: Weekly engineering changelog from merged PRs -- posted to Slack
enabled: false

trigger:
  kind: cron
  config:
    schedule: "0 9 * * 1"         # Every Monday at 9:00 AM
    working_dir: "."

sources:
  - kind: github-merged-prs
    label: "GitHub Merged PRs"
    config:
      repos:
        - saltyskip/cthulu
        - bitcoin-portal/bcom-zanoalias-v2
      since_days: 7

executors:
  # First pass: pre-process and structure the PR data
  - kind: claude-code
    label: "Executor - E01: pre-process"
    config:
      prompt: examples/prompts/dev_changelog.md

  # Second pass: finalize the changelog with formatting
  - kind: claude-code
    label: "Executor - E02: finalize"
    config:
      prompt: examples/prompts/dev_changelog.md

sinks:
  - kind: slack
    config:
      webhook_url_env: SLACK_WEBHOOK_URL
