# ============================================================================
# orangerock-newsletter
# ============================================================================
# Weekly crypto newsletter draft from curated sources.
# Runs every Monday at 8 AM, pulls latest 20 articles from 5 top crypto
# news outlets, generates X/Twitter-ready posts via Claude, and delivers
# the compiled newsletter to a Notion database.
#
# Pipeline: cron --> 5x RSS --> claude-code --> notion
# ============================================================================

name: orangerock-newsletter
description: Weekly crypto newsletter draft from curated sources
enabled: false

trigger:
  kind: cron
  config:
    schedule: "0 8 * * 1"         # Every Monday at 8:00 AM
    working_dir: "."

sources:
  - kind: rss
    label: "RSS: thedefiant.io"
    config:
      url: "https://thedefiant.io/feed"
      limit: 20

  - kind: rss
    label: "RSS: blockworks.co"
    config:
      url: "https://blockworks.co/feed"
      limit: 20

  - kind: rss
    label: "RSS: www.dlnews.com"
    config:
      url: "https://www.dlnews.com/feed/"
      limit: 20

  - kind: rss
    label: "RSS: www.theblock.co"
    config:
      url: "https://www.theblock.co/rss"
      limit: 20

  - kind: rss
    label: "RSS: unchainedcrypto.com"
    config:
      url: "https://unchainedcrypto.com/feed/"
      limit: 20

executors:
  - kind: claude-code
    label: "Claude: crypto_news_brief.md"
    config:
      prompt: examples/prompts/crypto_news_brief.md
      permissions:
        - Bash
        - Read
        - Grep
        - Glob

sinks:
  - kind: notion
    config:
      token_env: NOTION_TOKEN
      database_id: "REPLACE_WITH_YOUR_NOTION_DATABASE_UUID"
